sudo: false
dist: trusty
language: cpp
before_install: mkdir -p ${HOME}/usr/

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang
      install: export CXX="clang++" CC="clang"

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['g++-5']
      install: export CXX="g++-5" CC="gcc-5"

    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['g++-7']
      install: export CXX="g++-7" CC="gcc-7"

    - os: linux
      compiler: clang-3.5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['clang-3.5', 'libstdc++-4.9-dev']
      install: export CXX="clang++-3.5" CC="clang-3.5"

before_script:
  - mkdir build-release build-debug && cd build-debug
  - git clone https://github.com/hannespetur/boost-header-only.git
  - export BOOST_ROOT=$(pwd)/boost-header-only/boost-1.61.0
  - echo $BOOST_ROOT

script:
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
  - VERBOSE=1 make -j2
  - make check
  - cd ../build-release
  - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/usr/ ..
  - VERBOSE=1 make -j2
  - make install
